# Generated by Django 5.0.6 on 2024-06-28 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_rename_name_product_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='shipment',
            options={'ordering': ['date']},
        ),
        migrations.RemoveField(
            model_name='client',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='shipment_id',
        ),
    ]
