# Generated by Django 5.0.6 on 2024-06-28 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_alter_client_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='shipment_mode',
            field=models.CharField(default='standard', max_length=15),
        ),
    ]
